### ISSUE TITLE
Incorrect DB driver settings

### ISSUE THREAD

**Issue by roansong** [OOPMan/span-digital-exercise#1]
Hello Sir OOPMan I tried to run your cool program but I am encountering this error when trying to specify a DB other than the default. 

I created a `spandigitalexercise` table in my local MySQL.
Here is the command I tried to run:

```
java -jar span-digital-exercise-1.0.jar -d jdbc:mysql://root@localhost:3306/spandigitalexercise --use-sample-data
```

I received the following error:

```
Failed to get driver instance for jdbcUrl=jdbc:mysql://root@localhost:3306/spandigitalexercise
```

Here is the full traceback:

```
Exception in thread "main" java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://root@localhost:3306/spandigitalexercise
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:110)
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:342)
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:117)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:107)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
	at com.github.oopman.spandigitalexercise.CLI$.apply(CLI.scala:91)
	at com.github.oopman.spandigitalexercise.Main$.delayedEndpoint$com$github$oopman$spandigitalexercise$Main$1(Main.scala:7)
	at com.github.oopman.spandigitalexercise.Main$delayedInit$body.apply(Main.scala:6)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.github.oopman.spandigitalexercise.Main$.main(Main.scala:6)
	at com.github.oopman.spandigitalexercise.Main.main(Main.scala)
Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315)
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:103)
	... 16 more
```

**Comment by OOPMan** [comment]
@roansong Turns out the JDBI URI syntax for drivers is a little different:

Try: `jdbc:mysql://localhost:3306/spandigitalexercise?user=root`

**Comment by roansong** [comment]
@OOPMan unfortunately this has not solved my issue; I am continuing to receive the same error as above
